In [1]:
import pandas as pd
data=pd.read_csv('students.csv',parse_dates=["Score Date"])
data

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2     Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3     Omar   19   65.0       Math        Giza   False 2025-01-20
3           4     Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5   Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
5           6     Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7     Yara   30   89.0       Math       Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12

In [2]:
print(data.shape)
print(data.columns)
print(data.dtypes)

(9, 8)
Index(['Student ID', 'Name', 'Age', 'Grade', 'Subject', 'City', 'Passed',
       'Score Date'],
      dtype='object')
Student ID             int64
Name                  object
Age                    int64
Grade                float64
Subject               object
City                  object
Passed                  bool
Score Date    datetime64[ns]
dtype: object

In [3]:
data[:7]

   Student ID    Name  Age  Grade    Subject        City  Passed Score Date
0           1   Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2    Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3    Omar   19   65.0       Math        Giza   False 2025-01-20
3           4    Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5  Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
5           6    Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7    Yara   30   89.0       Math       Cairo    True        NaT

In [4]:
data[-3:]

   Student ID     Name  Age  Grade    Subject   City  Passed Score Date
6           7     Yara   30   89.0       Math  Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry   Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry   Giza    True 2025-03-12

In [5]:
data.isna().sum()

Student ID    0
Name          0
Age           0
Grade         1
Subject       0
City          0
Passed        0
Score Date    1
dtype: int64

In [6]:
print('Average:',data['Grade'].mean())
print('Minimum:',data['Grade'].min())
print('Maximum:',data['Grade'].max())

Average: 76.375
Minimum: 55.0
Maximum: 92.0

In [7]:
print(data['City'].nunique(),data['City'].unique())

4 ['Cairo' 'Alexandria' 'Giza' 'Mansoura']

In [8]:
data['Subject'].value_counts()

Subject
Math         3
Chemistry    3
Physics      2
English      1
Name: count, dtype: int64

In [9]:
data[['Name','Grade','Subject','City']]

      Name  Grade    Subject        City
0    Ahmed   88.0       Math       Cairo
1     Sara   92.0    Physics  Alexandria
2     Omar   65.0       Math        Giza
3     Lina   78.0  Chemistry       Cairo
4   Khaled   55.0    Physics    Mansoura
5     Nour    NaN    English  Alexandria
6     Yara   89.0       Math       Cairo
7  Mohamed   72.0  Chemistry        Giza
8  Mohamed   72.0  Chemistry        Giza

In [10]:
data[(data['Passed']==True)& (data['Grade']>=85)]

   Student ID   Name  Age  Grade  Subject        City  Passed Score Date
0           1  Ahmed   25   88.0     Math       Cairo    True 2025-01-15
1           2   Sara   32   92.0  Physics  Alexandria    True 2025-02-10
6           7   Yara   30   89.0     Math       Cairo    True        NaT

In [11]:
data[data['Name'].str.contains('a',case=False)]

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2     Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3     Omar   19   65.0       Math        Giza   False 2025-01-20
3           4     Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5   Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
6           7     Yara   30   89.0       Math       Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12

In [12]:
data[(data['City'].isin(['Cairo','Alexandria']))& (data['Grade']<80)]

   Student ID  Name  Age  Grade    Subject   City  Passed Score Date
3           4  Lina   28   78.0  Chemistry  Cairo    True 2025-03-05

In [13]:
data[data['Grade'].between(80,90)]

   Student ID   Name  Age  Grade Subject   City  Passed Score Date
0           1  Ahmed   25   88.0    Math  Cairo    True 2025-01-15
6           7   Yara   30   89.0    Math  Cairo    True        NaT

In [14]:
data.loc[data['Name']=='Khaled','Grade']=68

In [15]:
data

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2     Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3     Omar   19   65.0       Math        Giza   False 2025-01-20
3           4     Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5   Khaled   45   68.0    Physics    Mansoura   False 2025-02-28
5           6     Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7     Yara   30   89.0       Math       Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12

In [16]:
data['Is_Excellent']=data['Grade'].apply(lambda x: 'True' if x>=90 else 'False')
data

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False
5,6,Nour,22,NaN,English,Alexandria,True,2025-01-10,False
6,7,Yara,30,89.0,Math,Cairo,True,NaT,False
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False

In [17]:
data['Grade']=data['Grade'].fillna(data['Grade'].mean())
data

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False
6,7,Yara,30,89.0,Math,Cairo,True,NaT,False
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False

In [24]:
data['Score Date']=data['Score Date'].fillna(data['Score Date'].mode()[0])
data['Score Date']

C:\Users\MOHMMED\AppData\Local\Temp\ipykernel_28768\1619965308.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Score Date']=data['Score Date'].fillna(data['Score Date'].mode()[0])

0   2025-01-15
1   2025-02-10
2   2025-01-20
3   2025-03-05
4   2025-02-28
5   2025-01-10
6   2025-03-12
7   2025-03-12
8   2025-03-12
Name: Score Date, dtype: datetime64[ns]

In [25]:
data['Final_Grade']=data['Grade']+5
data

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False,73.0
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0
6,7,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0

In [26]:
data['Grade_Category']=pd.cut(data['Grade'],bins=[0,69,79,89,100],labels=['Fail','Average','Good','Excellent'],
                    include_lowest=True)
data

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0,Fail
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
4,5,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False,73.0,Fail
5,6,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
6,7,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [28]:
data=data.drop(columns='Student ID')
data

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
2,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0,Fail
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
4,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False,73.0,Fail
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [29]:
data=data[data['Passed']==True]
data

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [31]:
data=data.sort_values('Grade',ascending=False)
data

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [32]:
data=data.sort_values(['City','Grade'],ascending=[True,False])
data

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [33]:
data['Rank']=data['Grade'].rank(ascending=False,method='min')
data

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent,1.0
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average,4.0
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good,2.0
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good,3.0
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average,4.0
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0

In [34]:
data.nlargest(4,'Grade')

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent,1.0
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good,2.0
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good,3.0
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average,4.0

In [35]:
data.nsmallest(3,'Age')

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average,4.0
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good,3.0
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0

In [37]:
max_grades=data['Grade'].max()
highest_students=data[data['Grade']==max_grades][['Name','Grade']]
highest_students

   Name  Grade
1  Sara   92.0

In [ ]:
avg_per_subject=data.groupby('Subject')['Grade'].mean()
print('Average Grade per subject:\n',avg_per_subject)

Average Grade per subject:
 Subject
Chemistry    74.0
English      78.0
Math         88.5
Physics      92.0
Name: Grade, dtype: float64

In [ ]:
data['City_Avg']=data.groupby('City')['Grade'].transform('mean')
data

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank,City_Avg
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent,1.0,85.0
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average,4.0,85.0
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good,2.0,85.0
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good,3.0,85.0
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average,4.0,85.0
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0,72.0
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0,72.0

In [54]:
avg_grades=data.groupby('Subject')['Grade'].mean()
print(avg_grades)
top_subject=avg_grades.idxmax()
print(top_subject)

Subject
Chemistry    74.0
English      78.0
Math         88.5
Physics      92.0
Name: Grade, dtype: float64
Physics